import Event from "../../src/component/event";

describe('Event', () => {
    const mockedCreateEventElement = jest
    .spyOn(Event.prototype, 'createEventElement')
    .mockImplementation(() => {});

    document.body.innerHTML = `
    <div id="week-slots">
        <div class="prev-week-slots" data-week-start="2023-04-10">
            <div data-dayindex="0" class="day-slots">           
            <div data-hour="0" class="slot"></div><div data-hour="1" class="slot"></div><div data-hour="2" class="slot"></div><div data-hour="3" class="slot"></div><div data-hour="4" class="slot"></div><div data-hour="5" class="slot"></div><div data-hour="6" class="slot"></div><div data-hour="7" class="slot"></div><div data-hour="8" class="slot"></div><div data-hour="9" class="slot"></div><div data-hour="10" class="slot"></div><div data-hour="11" class="slot"></div><div data-hour="12" class="slot"></div><div data-hour="13" class="slot"></div><div data-hour="14" class="slot"></div><div data-hour="15" class="slot"></div><div data-hour="16" class="slot"></div><div data-hour="17" class="slot"></div><div data-hour="18" class="slot"></div><div data-hour="19" class="slot"></div><div data-hour="20" class="slot"></div><div data-hour="21" class="slot"></div><div data-hour="22" class="slot"></div><div data-hour="23" class="slot"></div></div>
            <div data-dayindex="1" class="day-slots">           
            <div data-hour="0" class="slot"></div><div data-hour="1" class="slot"></div><div data-hour="2" class="slot"></div><div data-hour="3" class="slot"></div><div data-hour="4" class="slot"></div><div data-hour="5" class="slot"></div><div data-hour="6" class="slot"></div><div data-hour="7" class="slot"></div><div data-hour="8" class="slot"></div><div data-hour="9" class="slot"></div><div data-hour="10" class="slot"></div><div data-hour="11" class="slot"></div><div data-hour="12" class="slot"></div><div data-hour="13" class="slot"></div><div data-hour="14" class="slot"></div><div data-hour="15" class="slot"></div><div data-hour="16" class="slot"></div><div data-hour="17" class="slot"></div><div data-hour="18" class="slot"></div><div data-hour="19" class="slot"></div><div data-hour="20" class="slot"></div><div data-hour="21" class="slot"></div><div data-hour="22" class="slot"></div><div data-hour="23" class="slot"></div></div>
            <div data-dayindex="2" class="day-slots">           
            <div data-hour="0" class="slot"></div><div data-hour="1" class="slot"></div><div data-hour="2" class="slot"></div><div data-hour="3" class="slot"></div><div data-hour="4" class="slot"></div><div data-hour="5" class="slot"></div><div data-hour="6" class="slot"></div><div data-hour="7" class="slot"></div><div data-hour="8" class="slot"></div><div data-hour="9" class="slot"></div><div data-hour="10" class="slot"></div><div data-hour="11" class="slot"></div><div data-hour="12" class="slot"></div><div data-hour="13" class="slot"></div><div data-hour="14" class="slot"></div><div data-hour="15" class="slot"></div><div data-hour="16" class="slot"></div><div data-hour="17" class="slot"></div><div data-hour="18" class="slot"></div><div data-hour="19" class="slot"></div><div data-hour="20" class="slot"></div><div data-hour="21" class="slot"></div><div data-hour="22" class="slot"></div><div data-hour="23" class="slot"></div></div>
            <div data-dayindex="3" class="day-slots">            
            <div data-hour="0" class="slot"></div><div data-hour="1" class="slot"></div><div data-hour="2" class="slot"></div><div data-hour="3" class="slot"></div><div data-hour="4" class="slot"></div><div data-hour="5" class="slot"></div><div data-hour="6" class="slot"></div><div data-hour="7" class="slot"></div><div data-hour="8" class="slot"></div><div data-hour="9" class="slot"></div><div data-hour="10" class="slot"></div><div data-hour="11" class="slot"></div><div data-hour="12" class="slot"></div><div data-hour="13" class="slot"></div><div data-hour="14" class="slot"></div><div data-hour="15" class="slot"></div><div data-hour="16" class="slot"></div><div data-hour="17" class="slot"></div><div data-hour="18" class="slot"></div><div data-hour="19" class="slot"></div><div data-hour="20" class="slot"></div><div data-hour="21" class="slot"></div><div data-hour="22" class="slot"></div><div data-hour="23" class="slot"></div></div>
            <div data-dayindex="4" class="day-slots">           
            <div data-hour="0" class="slot"></div><div data-hour="1" class="slot"></div><div data-hour="2" class="slot"></div><div data-hour="3" class="slot"></div><div data-hour="4" class="slot"></div><div data-hour="5" class="slot"></div><div data-hour="6" class="slot"></div><div data-hour="7" class="slot"></div><div data-hour="8" class="slot"></div><div data-hour="9" class="slot"></div><div data-hour="10" class="slot"></div><div data-hour="11" class="slot"></div><div data-hour="12" class="slot"></div><div data-hour="13" class="slot"></div><div data-hour="14" class="slot"></div><div data-hour="15" class="slot"></div><div data-hour="16" class="slot"></div><div data-hour="17" class="slot"></div><div data-hour="18" class="slot"></div><div data-hour="19" class="slot"></div><div data-hour="20" class="slot"></div><div data-hour="21" class="slot"></div><div data-hour="22" class="slot"></div><div data-hour="23" class="slot"></div></div>
            <div data-dayindex="5" class="day-slots">            
            <div data-hour="0" class="slot"></div><div data-hour="1" class="slot"></div><div data-hour="2" class="slot"></div><div data-hour="3" class="slot"></div><div data-hour="4" class="slot"></div><div data-hour="5" class="slot"></div><div data-hour="6" class="slot"></div><div data-hour="7" class="slot"></div><div data-hour="8" class="slot"></div><div data-hour="9" class="slot"></div><div data-hour="10" class="slot"></div><div data-hour="11" class="slot"></div><div data-hour="12" class="slot"></div><div data-hour="13" class="slot"></div><div data-hour="14" class="slot"></div><div data-hour="15" class="slot"></div><div data-hour="16" class="slot"></div><div data-hour="17" class="slot"></div><div data-hour="18" class="slot"></div><div data-hour="19" class="slot"></div><div data-hour="20" class="slot"></div><div data-hour="21" class="slot"></div><div data-hour="22" class="slot"></div><div data-hour="23" class="slot"></div></div>
            <div data-dayindex="6" class="day-slots">           
            <div data-hour="0" class="slot"></div><div data-hour="1" class="slot"></div><div data-hour="2" class="slot"></div><div data-hour="3" class="slot"></div><div data-hour="4" class="slot"></div><div data-hour="5" class="slot"></div><div data-hour="6" class="slot"></div><div data-hour="7" class="slot"></div><div data-hour="8" class="slot"></div><div data-hour="9" class="slot"></div><div data-hour="10" class="slot"></div><div data-hour="11" class="slot"></div><div data-hour="12" class="slot"></div><div data-hour="13" class="slot"></div><div data-hour="14" class="slot"></div><div data-hour="15" class="slot"></div><div data-hour="16" class="slot"></div><div data-hour="17" class="slot"></div><div data-hour="18" class="slot"></div><div data-hour="19" class="slot"></div><div data-hour="20" class="slot"></div><div data-hour="21" class="slot"></div><div data-hour="22" class="slot"></div><div data-hour="23" class="slot"></div></div>
        </div>
        <div class="main-week-slots" data-week-start="2023-04-17">
            <div data-dayindex="0" class="day-slots">           
            <div data-hour="0" class="slot"></div><div data-hour="1" class="slot"></div><div data-hour="2" class="slot"></div><div data-hour="3" class="slot"></div><div data-hour="4" class="slot"></div><div data-hour="5" class="slot"></div><div data-hour="6" class="slot"></div><div data-hour="7" class="slot"></div><div data-hour="8" class="slot"></div><div data-hour="9" class="slot"></div><div data-hour="10" class="slot"></div><div data-hour="11" class="slot"></div><div data-hour="12" class="slot"></div><div data-hour="13" class="slot"></div><div data-hour="14" class="slot"></div><div data-hour="15" class="slot"></div><div data-hour="16" class="slot"></div><div data-hour="17" class="slot"></div><div data-hour="18" class="slot"></div><div data-hour="19" class="slot"></div><div data-hour="20" class="slot"></div><div data-hour="21" class="slot"></div><div data-hour="22" class="slot"></div><div data-hour="23" class="slot"></div></div>
            <div data-dayindex="1" class="day-slots">           
            <div data-hour="0" class="slot"></div><div data-hour="1" class="slot"></div><div data-hour="2" class="slot"></div><div data-hour="3" class="slot"></div><div data-hour="4" class="slot"></div><div data-hour="5" class="slot"></div><div data-hour="6" class="slot"></div><div data-hour="7" class="slot"></div><div data-hour="8" class="slot"></div><div data-hour="9" class="slot"></div><div data-hour="10" class="slot"></div><div data-hour="11" class="slot"></div><div data-hour="12" class="slot"></div><div data-hour="13" class="slot"></div><div data-hour="14" class="slot"></div><div data-hour="15" class="slot"></div><div data-hour="16" class="slot"></div><div data-hour="17" class="slot"></div><div data-hour="18" class="slot"></div><div data-hour="19" class="slot"></div><div data-hour="20" class="slot"></div><div data-hour="21" class="slot"></div><div data-hour="22" class="slot"></div><div data-hour="23" class="slot"></div></div>
            <div data-dayindex="2" class="day-slots">           
            <div data-hour="0" class="slot"></div><div data-hour="1" class="slot"></div><div data-hour="2" class="slot"></div><div data-hour="3" class="slot"></div><div data-hour="4" class="slot"></div><div data-hour="5" class="slot"></div><div data-hour="6" class="slot"></div><div data-hour="7" class="slot"></div><div data-hour="8" class="slot"></div><div data-hour="9" class="slot"></div><div data-hour="10" class="slot"></div><div data-hour="11" class="slot"></div><div data-hour="12" class="slot"></div><div data-hour="13" class="slot"></div><div data-hour="14" class="slot"></div><div data-hour="15" class="slot"></div><div data-hour="16" class="slot"></div><div data-hour="17" class="slot"></div><div data-hour="18" class="slot"></div><div data-hour="19" class="slot"></div><div data-hour="20" class="slot"></div><div data-hour="21" class="slot"></div><div data-hour="22" class="slot"></div><div data-hour="23" class="slot"></div><div class="event mark" id="01GYB63ER0YZ9VBE1X0S8ANN9Z" style="background: var(--green); top: 101px; bottom: 1030px;"><img class="event-img" src="../icons/pm-w.png"><p class="event-number">1</p></div></div>
            <div data-dayindex="3" class="day-slots">            
            <div data-hour="0" class="slot"></div><div data-hour="1" class="slot"></div><div data-hour="2" class="slot"></div><div data-hour="3" class="slot"></div><div data-hour="4" class="slot"></div><div data-hour="5" class="slot"></div><div data-hour="6" class="slot"></div><div data-hour="7" class="slot"></div><div data-hour="8" class="slot"></div><div data-hour="9" class="slot"></div><div data-hour="10" class="slot"></div><div data-hour="11" class="slot"></div><div data-hour="12" class="slot"></div><div data-hour="13" class="slot"></div><div data-hour="14" class="slot"></div><div data-hour="15" class="slot"></div><div data-hour="16" class="slot"></div><div data-hour="17" class="slot"></div><div data-hour="18" class="slot"></div><div data-hour="19" class="slot"></div><div data-hour="20" class="slot"></div><div data-hour="21" class="slot"></div><div data-hour="22" class="slot"></div><div data-hour="23" class="slot"></div></div>
            <div data-dayindex="4" class="day-slots">           
            <div data-hour="0" class="slot"></div><div data-hour="1" class="slot"></div><div data-hour="2" class="slot"></div><div data-hour="3" class="slot"></div><div data-hour="4" class="slot"></div><div data-hour="5" class="slot"></div><div data-hour="6" class="slot"></div><div data-hour="7" class="slot"></div><div data-hour="8" class="slot"></div><div data-hour="9" class="slot"></div><div data-hour="10" class="slot"></div><div data-hour="11" class="slot"></div><div data-hour="12" class="slot"></div><div data-hour="13" class="slot"></div><div data-hour="14" class="slot"></div><div data-hour="15" class="slot"></div><div data-hour="16" class="slot"></div><div data-hour="17" class="slot"></div><div data-hour="18" class="slot"></div><div data-hour="19" class="slot"></div><div data-hour="20" class="slot"></div><div data-hour="21" class="slot"></div><div data-hour="22" class="slot"></div><div data-hour="23" class="slot"></div></div>
            <div data-dayindex="5" class="day-slots">            
            <div data-hour="0" class="slot"></div><div data-hour="1" class="slot"></div><div data-hour="2" class="slot"></div><div data-hour="3" class="slot"></div><div data-hour="4" class="slot"></div><div data-hour="5" class="slot"></div><div data-hour="6" class="slot"></div><div data-hour="7" class="slot"></div><div data-hour="8" class="slot"></div><div data-hour="9" class="slot"></div><div data-hour="10" class="slot"></div><div data-hour="11" class="slot"></div><div data-hour="12" class="slot"></div><div data-hour="13" class="slot"></div><div data-hour="14" class="slot"></div><div data-hour="15" class="slot"></div><div data-hour="16" class="slot"></div><div data-hour="17" class="slot"></div><div data-hour="18" class="slot"></div><div data-hour="19" class="slot"></div><div data-hour="20" class="slot"></div><div data-hour="21" class="slot"></div><div data-hour="22" class="slot"></div><div data-hour="23" class="slot"></div></div>
            <div data-dayindex="6" class="day-slots">           
            <div data-hour="0" class="slot"></div><div data-hour="1" class="slot"></div><div data-hour="2" class="slot"></div><div data-hour="3" class="slot"></div><div data-hour="4" class="slot"></div><div data-hour="5" class="slot"></div><div data-hour="6" class="slot"></div><div data-hour="7" class="slot"></div><div data-hour="8" class="slot"></div><div data-hour="9" class="slot"></div><div data-hour="10" class="slot"></div><div data-hour="11" class="slot"></div><div data-hour="12" class="slot"></div><div data-hour="13" class="slot"></div><div data-hour="14" class="slot"></div><div data-hour="15" class="slot"></div><div data-hour="16" class="slot"></div><div data-hour="17" class="slot"></div><div data-hour="18" class="slot"></div><div data-hour="19" class="slot"></div><div data-hour="20" class="slot"></div><div data-hour="21" class="slot"></div><div data-hour="22" class="slot"></div><div data-hour="23" class="slot"></div></div>
        </div>
        <div class="next-week-slots" data-week-start="2023-05-01">
            <div data-dayindex="0" class="day-slots">           
            <div data-hour="0" class="slot"></div><div data-hour="1" class="slot"></div><div data-hour="2" class="slot"></div><div data-hour="3" class="slot"></div><div data-hour="4" class="slot"></div><div data-hour="5" class="slot"></div><div data-hour="6" class="slot"></div><div data-hour="7" class="slot"></div><div data-hour="8" class="slot"></div><div data-hour="9" class="slot"></div><div data-hour="10" class="slot"></div><div data-hour="11" class="slot"></div><div data-hour="12" class="slot"></div><div data-hour="13" class="slot"></div><div data-hour="14" class="slot"></div><div data-hour="15" class="slot"></div><div data-hour="16" class="slot"></div><div data-hour="17" class="slot"></div><div data-hour="18" class="slot"></div><div data-hour="19" class="slot"></div><div data-hour="20" class="slot"></div><div data-hour="21" class="slot"></div><div data-hour="22" class="slot"></div><div data-hour="23" class="slot"></div></div>
            <div data-dayindex="1" class="day-slots">           
            <div data-hour="0" class="slot"></div><div data-hour="1" class="slot"></div><div data-hour="2" class="slot"></div><div data-hour="3" class="slot"></div><div data-hour="4" class="slot"></div><div data-hour="5" class="slot"></div><div data-hour="6" class="slot"></div><div data-hour="7" class="slot"></div><div data-hour="8" class="slot"></div><div data-hour="9" class="slot"></div><div data-hour="10" class="slot"></div><div data-hour="11" class="slot"></div><div data-hour="12" class="slot"></div><div data-hour="13" class="slot"></div><div data-hour="14" class="slot"></div><div data-hour="15" class="slot"></div><div data-hour="16" class="slot"></div><div data-hour="17" class="slot"></div><div data-hour="18" class="slot"></div><div data-hour="19" class="slot"></div><div data-hour="20" class="slot"></div><div data-hour="21" class="slot"></div><div data-hour="22" class="slot"></div><div data-hour="23" class="slot"></div></div>
            <div data-dayindex="2" class="day-slots">           
            <div data-hour="0" class="slot"></div><div data-hour="1" class="slot"></div><div data-hour="2" class="slot"></div><div data-hour="3" class="slot"></div><div data-hour="4" class="slot"></div><div data-hour="5" class="slot"></div><div data-hour="6" class="slot"></div><div data-hour="7" class="slot"></div><div data-hour="8" class="slot"></div><div data-hour="9" class="slot"></div><div data-hour="10" class="slot"></div><div data-hour="11" class="slot"></div><div data-hour="12" class="slot"></div><div data-hour="13" class="slot"></div><div data-hour="14" class="slot"></div><div data-hour="15" class="slot"></div><div data-hour="16" class="slot"></div><div data-hour="17" class="slot"></div><div data-hour="18" class="slot"></div><div data-hour="19" class="slot"></div><div data-hour="20" class="slot"></div><div data-hour="21" class="slot"></div><div data-hour="22" class="slot"></div><div data-hour="23" class="slot"></div></div>
            <div data-dayindex="3" class="day-slots">            
            <div data-hour="0" class="slot"></div><div data-hour="1" class="slot"></div><div data-hour="2" class="slot"></div><div data-hour="3" class="slot"></div><div data-hour="4" class="slot"></div><div data-hour="5" class="slot"></div><div data-hour="6" class="slot"></div><div data-hour="7" class="slot"></div><div data-hour="8" class="slot"></div><div data-hour="9" class="slot"></div><div data-hour="10" class="slot"></div><div data-hour="11" class="slot"></div><div data-hour="12" class="slot"></div><div data-hour="13" class="slot"></div><div data-hour="14" class="slot"></div><div data-hour="15" class="slot"></div><div data-hour="16" class="slot"></div><div data-hour="17" class="slot"></div><div data-hour="18" class="slot"></div><div data-hour="19" class="slot"></div><div data-hour="20" class="slot"></div><div data-hour="21" class="slot"></div><div data-hour="22" class="slot"></div><div data-hour="23" class="slot"></div></div>
            <div data-dayindex="4" class="day-slots">           
            <div data-hour="0" class="slot"></div><div data-hour="1" class="slot"></div><div data-hour="2" class="slot"></div><div data-hour="3" class="slot"></div><div data-hour="4" class="slot"></div><div data-hour="5" class="slot"></div><div data-hour="6" class="slot"></div><div data-hour="7" class="slot"></div><div data-hour="8" class="slot"></div><div data-hour="9" class="slot"></div><div data-hour="10" class="slot"></div><div data-hour="11" class="slot"></div><div data-hour="12" class="slot"></div><div data-hour="13" class="slot"></div><div data-hour="14" class="slot"></div><div data-hour="15" class="slot"></div><div data-hour="16" class="slot"></div><div data-hour="17" class="slot"></div><div data-hour="18" class="slot"></div><div data-hour="19" class="slot"></div><div data-hour="20" class="slot"></div><div data-hour="21" class="slot"></div><div data-hour="22" class="slot"></div><div data-hour="23" class="slot"></div></div>
            <div data-dayindex="5" class="day-slots">            
            <div data-hour="0" class="slot"></div><div data-hour="1" class="slot"></div><div data-hour="2" class="slot"></div><div data-hour="3" class="slot"></div><div data-hour="4" class="slot"></div><div data-hour="5" class="slot"></div><div data-hour="6" class="slot"></div><div data-hour="7" class="slot"></div><div data-hour="8" class="slot"></div><div data-hour="9" class="slot"></div><div data-hour="10" class="slot"></div><div data-hour="11" class="slot"></div><div data-hour="12" class="slot"></div><div data-hour="13" class="slot"></div><div data-hour="14" class="slot"></div><div data-hour="15" class="slot"></div><div data-hour="16" class="slot"></div><div data-hour="17" class="slot"></div><div data-hour="18" class="slot"></div><div data-hour="19" class="slot"></div><div data-hour="20" class="slot"></div><div data-hour="21" class="slot"></div><div data-hour="22" class="slot"></div><div data-hour="23" class="slot"></div></div>
            <div data-dayindex="6" class="day-slots">           
            <div data-hour="0" class="slot"></div><div data-hour="1" class="slot"></div><div data-hour="2" class="slot"></div><div data-hour="3" class="slot"></div><div data-hour="4" class="slot"></div><div data-hour="5" class="slot"></div><div data-hour="6" class="slot"></div><div data-hour="7" class="slot"></div><div data-hour="8" class="slot"></div><div data-hour="9" class="slot"></div><div data-hour="10" class="slot"></div><div data-hour="11" class="slot"></div><div data-hour="12" class="slot"></div><div data-hour="13" class="slot"></div><div data-hour="14" class="slot"></div><div data-hour="15" class="slot"></div><div data-hour="16" class="slot"></div><div data-hour="17" class="slot"></div><div data-hour="18" class="slot"></div><div data-hour="19" class="slot"></div><div data-hour="20" class="slot"></div><div data-hour="21" class="slot"></div><div data-hour="22" class="slot"></div><div data-hour="23" class="slot"></div></div>
        </div>
    </div>
    `;

    it('should find existing week', () => {
        //init
        const event = new Event({
            weekStart: "2023-04-10",
            place: "",
            start: "12:00",
            end: "13:00",
            date: "2023-04-12",
            memberIds: ["1", "2"],
            color: "green",
            type: "pm", 
        });

        //invoke
        event.show();

        //check
        expect(mockedCreateEventElement).toHaveBeenCalledTimes(1);
    });

    it('should return null when no week is found', () => {
        //init
        const event = new Event({
            weekStart: "2023-05-08",
            place: "",
            start: "12:00",
            end: "13:00",
            date: "2023-04-12",
            memberIds: ["1", "2"],
            color: "green",
            type: "pm", 
        });

        //invoke
        event.show();

        //check
        expect(mockedCreateEventElement).toHaveBeenCalledTimes(0);
    });
});
