name: 'Test PRs'
on:
  pull_request:
    paths:
      - src/**
      - package-lock.json
      - .github/workflows/pr-test.yml
jobs:
  unit-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v3
        with: 
          node-version: 16
      - name: Cache Node.js modules
        uses: actions/cache@v3
        with:
          path: ~/.npm # npm cache files are stored in `~/.npm` on Linux/macOS
          key: ${{ runner.OS }}-node-16-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{runner.OS}}-node-16
            ${{runner.OS}}-
      - name: Install Dependencies
        run: npm ci
      - name: Build Project
        run: npm run build
      - name: Run Unit Tests
        id: apply
        run: npm run test:cov
      - name: Post Test Coverage Results to PR
        uses: romeovs/lcov-reporter-action@v0.3.1
        with:
          lcov-file: ./coverage/lcov.info
          github-token: ${{ secrets.GITHUB_TOKEN }}
