name: 'Test PRs'
on:
  pull_request:
    paths:
      - src/**
      - package-lock.json
      - .github/workflows/pr-test.yml
  workflow_dispatch:
permissions:
  id-token: write
  contents: read
  pull-requests: write
jobs:
  unit-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v3
        with: 
          node-version: 16
      - uses: actions/cache@v3
        name: Cache Node.js modules
        with:
          path: ~/.npm # npm cache files are stored in `~/.npm` on Linux/macOS
          key: ${{ runner.OS }}-node-16-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{runner.OS}}-node-16
            ${{runner.OS}}-
      - name: Install Dependencies
        run: npm ci
      - name: Build Project
        run: npm run build
      - name: Run Unit Tests
        id: apply
        run: npm run test:cov
      - name: Echo stdout
        run: echo "${{steps.apply.outputs.stdout}}"
      - uses: actions/github-script@v6
        with:
          script: |
            const apply = `${{ steps.apply.outputs.stdout }}`;
            return apply
